### PR TITLE
Feature setup

### PR DESCRIPTION
**Pull request by matheus-fls**
Requesting review

### CODE REVIEW

**Comment by matheus-fls** [comment]
According to the Microverse requirements:

"Milestone 7: Omniauth
Add an option to sign-in with a real Facebook account as described in requirements.
Remember about unit and integrations tests!"

We should do what you require only far ahead. 

But anyway we did our best to make your required changes.

**Comment by matheus-fls** [comment]
And also, about Devise:

"Milestone 3: Users & posts
Create models with associations and implement all requested features for users and posts. Add authentication with Devise as described in requirements.
Remember about unit and integrations tests!"

**Comment by matheus-fls** [comment]
I am not sure if you read the milestones, but it could help you to provide a meaningful review.

**Comment by matheus-fls** [comment]
Stickler is now up and running, submitting for another code review.

**Comment by AnthonyTC89** [comment]
Thanks for the review! We will consider the additional annotations in the Project.

**Pull request merged**
